### ISSUE TITLE
"Add subject" button functionality is not present.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1027]
**Description**
In the subjects screen we have a (plus) button to add the subjects, but the functionality is not yet added.

**Screenshot**
![Screenshot_2023-11-16-15-39-53-80_ddc0fec0f25cadbb53407d57e5100bc9](https://github.com/chimple/chimple/assets/99384703/151449ba-d54a-41b2-aa0a-1db33bae7e36)

**Comment by pratapramesh** [comment]
1. Here Student can add State board subjects and other board subjects
because of that English, Hindi, Maths Subjects displaying 2 times

![Screenshot_2024-04-04-12-42-37-047](https://github.com/chimple/cuba/assets/138564361/fa9e1e1a-f3b4-4ace-b2c4-c4101c8ffda1)

2. After Adding all the subject it is displaying blank screen
![Screenshot_2024-04-04-12-40-45-079](https://github.com/chimple/cuba/assets/138564361/b795d82d-5273-44c9-8a14-556fe00e3c99)

3. After adding 2-3 subject the 'Add subject' button got disappeared and it happend only one time

https://github.com/chimple/cuba/assets/138564361/92c5eed1-6ba5-48c3-b376-3f9f44233872

**Comment by pratapramesh** [comment]
[logs for add subject button disappear.txt](https://github.com/chimple/cuba/files/15010112/logs.for.add.subject.button.disappear.txt)

**Comment by pratapramesh** [comment]
[logs for add subject button disappear.txt](https://github.com/chimple/cuba/files/15019917/logs.for.add.subject.button.disappear.txt)
