### ISSUE TITLE
Dashboard report view [Homepage]

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1356]
Contains the main table

**Comment by RadhaG3** [comment]
<img width="1161" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeldyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b1536c12e9503ca07d7935763845aa2572439e1a/image.png" alt="image.png" />

**Comment by Pramodmarssun** [comment]
- Student profile is moving to green band even when multiple assignments are pending 
- We are not able to see the added courses when we click on drop-down

**Comment by Pramodmarssun** [comment]
1. Student played lesson data is not synching imidieatly in dashboard
2. Student profiles will be squeezed when there are more student proile in same band and when we click on band there student profiles will be expanded top to bottom
3. Average score is coming in decimal and its overlapping 
4. Number of assignment and Number of student summury is not updating 
5.  Text size is to small in all report 
6. Drop-Down alignment and there is gap between courses in dropdown

**Comment by Pramodmarssun** [comment]
- When we create a student profile by uploading the image, in band profile looks squeezed

**Comment by Pramodmarssun** [comment]
1. When we create a student profile by uploading the image, in band profile looks squeezed
2. Weekly summury band looks smaller on screen when we compared with mockup 

Screenshot:
![Dashboard](https://github.com/user-attachments/assets/b84b4ca3-647f-4b0c-ab6a-97bf35ad7439)


3. Text of the indicators in summury band is not matching mockup
       - Number of students 
       - Time spent

4. Instead of dispalying selected course details we are showing all courses details in Summury and in all bands

**Comment by Pramodmarssun** [comment]
To verify this story #1359 need to be fixed

**Comment by Pramodmarssun** [comment]
**Data Update Issues**

1. We have to restart the app to see the updated data.

**Functional Issues**

1. Average time spent is not correct; it is showing total time spent instead of average.
2. Every time we change the screen and come back to the dashboard, the first subject available in the dropdown is selected each time.

**UI/UX Issues**

1. Average time spent is coming in red color.
2. We can see padding behind the student profile in bands.
3. When we go inside the band, Lesson names are not completed.

**Screenshot**
![Screenshot_20241119_160759_Chimple](https://github.com/user-attachments/assets/cfb7d181-2ca5-4cd4-96a3-b643a2f6ec00)
![Screenshot_20241119_160749_Chimple](https://github.com/user-attachments/assets/a5ebbce8-ef9f-407e-912e-e29d7a7160e2)

**Comment by Pramodmarssun** [comment]
**Average Time Spent Display Issue:**

- The average time spent is displayed in decimal format for seconds (e.g., 12.5 seconds). It should be rounded or formatted to show whole seconds.

**Data Not Updating Automatically:**

- When changing screens and navigating back, the data does not update automatically. It only updates after performing a manual refresh.

**Comment by Pramodmarssun** [comment]
We can move this story to done
