### ISSUE TITLE
Assign screen functionality

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1359]

**Comment by RadhaG3** [comment]
**User Story**
As a Teacher, I should be able to assign the assignments to all the students of my class

**Acceptance Criteria**
(i) Given that user navigates to 'Assign' page
When clicked on '',
Then User to enter the below details

Class Name
(ii) Given that user navigates to 'Switch Class' button on a class page
When clicked on 'Switch Class',
Then User to choose the available classes

(iii) Given that user navigates to 'Delete Class' button on a class page
When User chooses to 'Delete Class',
Then class to be deleted

**Comment by divyahariharan2103** [comment]
Investigation for add screen and complete score

**Comment by Mary-Harshitha** [comment]
![image](https://github.com/chimple/cuba/assets/62737530/1479c2c7-1fc1-48d5-bc55-e736e6e346ab)

**Comment by Ashish1998** [comment]
**AssignButton**
- In Assign button, the text assign is not present on the button
- The size of the button is very small compared to the mockup.

**AssignmentAppBar**
- Here for Assignmentappbar component, instead of bar a arrow button is present which is not present in the mockup.

**AssignmentTabList**
- In Assignment tab list, in the provided mockup the tabs are horizontally aligned but here the tabs are vertical.

**ChapterCard**
- In Chapter card, the image added for the card is not presnet in the mockup.
- In the mockup the select button for the chapter is present at the right, but here in story book it is in the left side.
- Size of the card is very big compared to the mockup.

**DropDown**
- In the design the shape of the dropdown is rectangular, but here it is cricular in shape.
- Proper options are not present in the dropdown.

**DateTimePicker**
- In the datetimepicker, the alignment of the components are not proper.
- Here if we click on the Date to select the date the days, months and year options are not properly aligned.
- Time setting is not present in the storybook.
- If we change the device size still the component size is the same it is not adjusting to the particular size.

**Lesson icon**
- If we select the lesson card the image of the lesson moves down if we unselect it will move to the proper position.

**Recommended assignement**
- Here the check box for the lesson is to the left side not right
- In the mock up only text of the particular suggested lesson is present, but in story book image is present for every lesson.

**Recommended tab**
- here the tab is not present, some images are displayed.

**select all**
- Multiple options are not present to check select all.
- Select all text is not displayed.

**Comment by Pramodmarssun** [comment]
1. When selecting recommended assignments, they are not added to the total number of recommendations.
2. There is no default date for assignments; the user has to select it manually every time.
3. All bands are not selected when assigning homework; only two bands are selected.
4. After assigning the recommended homework, the same lesson is presented for assignment again instead of new lessons.
5. Clicking the "Select All" button causes the dropdowns to expand and close unexpectedly.
6. When assigning manually, after adding assignments from the Library, the "Next" button does not work.
7. The "Assign" button is clickable even when no assignments are selected, causing a long load time after clicking.
8. Manual or recommended courses should not be expanded by default according to the mockup. Users should choose the course, then the lesson.
9. There is no option to assign a Live Quiz.
10. Start and End date calendars should be the same. In Teacher Assignment Summary, the calendar is different.
11. In the Library, lessons can be added one by one. Can we add a button to select the entire chapter?
12. In story book this story is not coming

**Comment by Pramodmarssun** [comment]
Bugs

1. Assigned assignments do not appear in the student profile.
2. When adding lessons to the cart in the Library and clicking "Next," the selected lessons get deselected, so the user has to re-select them on the assignment screen.
3. If the teacher selects all recommended lessons and then deselects any individual lesson before assigning, the recommendations for the next assignment are affected.
4. Yellow and green bands can't be deselected.
5. The same student appears in two bands when we extend the band information.
6. Assignments or live quizzes can be scheduled with past start and end times.
7. When clicking the back button from the "Select Bands to Assign" screen, the selected lessons are deselected upon returning.
8. The calendar in this section does not match the one in the teacher summary.
9. This story is missing in Storybook.


UI

1. The mockup doesn't show the correct number of selected lessons or courses next to manual or recommended assignments.
2. "Manual" and "Recommended" text labels sometimes break into two lines instead of displaying in one line.
3. Some text is not visible in dark mode.
4. In the mockup, individual lessons and selected courses have different colors, but they appear the same here.
5. The calendar button appears black in dark mode.
6. On the "Select Date and Band" screen, the screen can scroll left to right; it should be fixed.
7. Student names are not visible in dark mode on the "Select Band" screen.
8. After clicking "Assign," only the "Share" button looks clickable; the "OK" button does not.
9. The share message lacks details about the assigned lessons.


Screenshots:
![Screenshot_20241108_114121_Chimple](https://github.com/user-attachments/assets/8c7b3911-7bdc-419d-a52c-7dd15fcfbf3f)
![Screenshot_20241108_114111_Chimple](https://github.com/user-attachments/assets/26860091-a283-4eea-bc20-81f71cbc8252)

**Comment by Pramodmarssun** [comment]
1. **Limited Date Selection in Calendar**
When selecting the date duration for an assignment, the Start Date calendar displays only the month of January 2025, regardless of the current date, limiting flexibility. Similarly, the End Date calendar allows only past dates to be selected, preventing users from setting future end dates for assignments.
2. **Deselection of Recommended Lessons**
When users select lessons from both the "Manual" and "Recommended" assignment sections, then navigate to the "Assignments" page and return, the recommended lessons are deselected automatically.
3. We are allowing user to assign assignment when there are no bands are selected 

**UI**
1. Assignment created confirmation looks same as before in some cases 
2. Assignment assigned sharing message is showing N/A instead of details 
3. We have Select All check box to select all bands to assign homework but when there are no students in any band user not allowed to select that but select all check box is checked 


**Screenshots**
1. 
![Screenshot_20241202_115718_Chimple](https://github.com/user-attachments/assets/250c2ae8-828a-4e44-80e1-57588964090c)
2. ![Screenshot_20241202_115751_WhatsApp](https://github.com/user-attachments/assets/b3639e8e-e276-4e8c-b790-0a99c6865096)
3. ![Screenshot_20241202_113546_Chimple](https://github.com/user-attachments/assets/78cc689d-6cdc-406c-9d87-9e6c2addafd5)

**Comment by Pramodmarssun** [comment]
1. When no band is selected, and the user tries to assign homework, the message "Please select the student" is displayed.
2. The start and end dates for the assignment are not accurate.
3. The selected number of manual assignments exceeds the available manual assignments
