### ISSUE TITLE
Add teachers

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1366]

**Comment by RadhaG3** [comment]
User Story
As a Teacher, I should be able to co-teachers to my class. Also, I should be able to edit/delete any relevant information related to my students if required so that I can manage my students.

Acceptance Criteria
(i) Given that User navigates to 'Add Student' button on the students page
When clicked on 'Add Student',
Then User to enter the below details

Student Name
Age
Student ID
Gender
Student Number
(ii) Given that User navigates to 'Edit Student' button on the students page
When clicked on 'Edit Student',
Then User to edit the below details

Student Name
Age
Student ID
Gender
Student Number
(iii) Given that User navigates to 'Delete Student' button on the students page
When clicked on 'Delete Student',
Then User to delete the chosen student

**Comment by Pramodmarssun** [comment]
- Delete user is not working 
- I am able to add the phone number to the class which already logged in as Principle 
- Search user button should be changed (it feels exit button)
- In Dark mode date calander is not visible

**Comment by Pramodmarssun** [comment]
1. Teacher name is not displaying in assignment assigned report screen in dark mode
2. After adding the user as teacher we have re-login to see the user in class user
3. When Principle click on delete, Delete function button is bigger
4. Assigned assignment by teacher, in this screen UI is not matching with mockup
5. When there are no assginment assigned by teacher we should show some text like user is not assigned anything yet 
6. Default date should be selected in assigned assignment summury

**Comment by Pramodmarssun** [comment]
UI Enhancement in Assignment Assigned Summury
- Select the start Date and End date for all the assignment. In this Start Date and End date should be highlighted with bold letters 
- When click on Start date calander icon, if we are clicking on already selected date calander is not disappearing unless we choose diffrent date 
- No Assignment found. This line shoud be below, it is closed to header of selected Date

**Comment by Pramodmarssun** [comment]
- Here complete user information is scrollable and screen can be utilized more 

https://github.com/user-attachments/assets/7894b700-1fd2-4816-ba08-9498da72dcdf

**Comment by Pramodmarssun** [comment]
- In year drop-down we can see only two months name and one month in end date
![Screenshot_2024-10-29-14-28-42-768](https://github.com/user-attachments/assets/16abea10-acf8-420d-b892-12c1e6c46e17)
