### ISSUE TITLE
Add School users

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1368]

**Comment by Pramodmarssun** [comment]
@vinaypanduga Please add some basic test cases

**Comment by Pramodmarssun** [comment]
**Add User Pop-up**

- [ ] Search text is not in middle of the screen pop-up box
- [ ] Pop-up close button is small in small devices screen
- [ ] Search button is small
- [ ] No space for **PhoneNumber** text in text field
- [ ] Use phone number or use email instead text's are close to text field box


**User Tabs** 

- [ ] Text's are In capital letter's in User tab's
- [ ] User tabs are not fitting the screen for selected device screen size

**Comment by pratapramesh** [comment]
- I have added 6 mail-id as a co-ordinators

![Screenshot_20241203_133137](https://github.com/user-attachments/assets/ba1792c6-795c-46bb-a626-71fbd356d612)

- one of those email-id, it's showing only 3 co-ordinators are there in that school

![Screenshot_20241203_132846](https://github.com/user-attachments/assets/293d6468-2c7b-47e0-bd2f-42756753bc74)

- for another email-id it's showing one co-ordinator

![Screenshot_20241203_134654](https://github.com/user-attachments/assets/1ada18ac-b121-4120-b087-551e061f4607)

- the school is showing twice for one co-ordinator

![Screenshot_20241203_135215](https://github.com/user-attachments/assets/410503f8-45d7-404c-8d66-45ea86867d8c)

- Above issues are same for principles , co-ordinators and sponsors

- Teachers are not able to see the co-ordinators

https://github.com/user-attachments/assets/3c0a37c9-f527-458e-b86f-f0b3ddcdccbc

- Instead of showing blank page, we can add text for users page
![Screenshot_20241204_093544 (1)](https://github.com/user-attachments/assets/95996bbb-944f-48de-bacb-41346894bf0c)

- here users header colour is too dark
<img width="960" alt="SnapCrab_NoName_2024-12-4_9-42-49_No-00" src="https://github.com/user-attachments/assets/d3a8660d-2b46-4ea8-861e-1be902e468fa">

**Comment by pratapramesh** [comment]
Certain email IDs and phone numbers cannot be added as Principal, coordinators and sponsors so for this created issue 1903
