### ISSUE TITLE
Redirected to Parent/Teacher mode selection screen if we close and reopen the app in profile screen.

### ISSUE THREAD

**Issue by Ashish1998** [chimple/cuba#1441]
**Description**
In the profile selection screen if we close the app and reopen it will again take us to Parent/ Teacher mode selection screen. This should appear only when the user logs In .

**Screen Record**

https://github.com/chimple/cuba/assets/99384703/45684cd6-4b89-4613-8179-3c6a00d5d505

**Comment by Pramodmarssun** [comment]
Currently, whenever we log in, we are directed to the Parent or Teacher mode selection page.

However, the issue arises because we store login data locally. As a result, whenever we install the Chimple app, it does not prompt for login credentials and instead directly takes us to the Parent account.

**Comment by Pramodmarssun** [comment]
We can close this issue with supabase Login issue will be resolved

**Comment by divyahariharan2103** [comment]
Re-estimating to 3 as nearly 3 days was taken
