### ISSUE TITLE
Child profile creation

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1532]

**Comment by Pramodmarssun** [comment]
**1. Grade Drop-Down Issue:**
**Problem:** The grade drop-down menu contains an extra option called "test" which needs to be removed.
**2. Profile Edit Issue:**
**Problem:** When editing a student profile and changing the board, the system displays both the previously selected board courses and the current board courses. The same issue occurs when changing the grade.
**3. Language Selection Issue:**
**Problem:** When the student language is chosen or changed, the parent language changes according to the student language.

**Comment by Pramodmarssun** [comment]
**1. Grade Drop-Down Issue:**
Problem: The grade drop-down menu contains an extra option called "test" which needs to be removed.
Status: Not resolved.
Comment: The "test" option is still present and needs to be removed.

**2. Language Selection Issue:**
Problem: When the student language is chosen or changed, the parent language changes accordingly.
Status: Issue reappears after restarting the app.
Comment: The parent language changes with the student language again after restarting the app. This needs fixing.

- **Steps to reproduce the above issue:**

1. Create student profile and choose Meduim of Instruction Hindi
2. Restart the app
3. Student profile will be signed out 
4. Here Parent languge will be changed English to Hindi 



**3. Student Profile Connection Issue:**
Problem: The student profile does not appear in the parent account after creation.
Status: Resolved.
Comment: The issue is resolved. The student profile now appears correctly in the parent account.
