### ISSUE TITLE
Adding the UP curriculum mapping

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#1623]

**Comment by Pramodmarssun** [comment]
**Maths G1** 
1. Chapter 14 is not opening 
2. Chapter 13 is not present in the app and in the sheet as well
3. Chapter 16 is not available in the app
4. Chapter 20 is not available in the app 
5. Chapter 21 lesson 1-20 and 2-30 name is not displaying instead of name some code is displayed 
6. Chapter 22 starting 2 lesson's missing 
7. Chapter 25 is missing

**Comment by Pramodmarssun** [comment]
Grade 1
1. Chapter 13 is not present in app 
2. Chapter 20 is not present in app
3. Chapter 22 lesson's are still missing

Grade 2
1. Chapter 02-1: Last lesson of the chapter is not showing properly
2. Chapter 02-1: 7th Lesson is not opening 
3. Chapter 09-1: 3 and 4th lesson name is not showing properly 
4. Chapter 20 is not present

**Comment by Pramodmarssun** [comment]
Grade 1
- Chapter 11: Lesson 4 not opening 
- Chapter 22: starting 2 lesson name is coming in English

**Comment by Pramodmarssun** [comment]
All issues has been fixed. we can close this story
