### ISSUE TITLE
 Subjects automatically scroll to last played one

### ISSUE THREAD

**Issue by divyahariharan2103** [chimple/cuba#642]

**Comment by Pramodmarssun** [comment]
- If we see the lesson cards after completing the lesson, we can see all the completed lessons are moving from right to left.
- When we complete a lesson in suggestion screen, we will get to see last played lesson but what we are suggesting a lesson to student, that will move to outside of the screen because in the suggestion screen 1st lesson is not played and 2nd lesson is played 

https://github.com/chimple/cuba/assets/108517798/a683a581-9665-4c35-a664-63cfc89a7ebe

**Comment by Pramodmarssun** [comment]
after removing last played lesson scrolling, now in suggestion screen it's working fine
We can move this to done
