### ISSUE TITLE
Issue in search screen

### ISSUE THREAD

**Issue by pratapramesh** [chimple/cuba#958]
- [ ] **Search bar is overlapping in Game**

Steps to reproduce

1. Search any lessoncard in search page
2. play the lesson card
3. while playing just click on mobile back button

![Screenshot_2023-10-09-15-37-21-174](https://github.com/chimple/cuba/assets/138564361/4fa70fe7-817e-400f-97c3-e6038f5e1523)

- [x] **In one of the device unable to search a lesson card in Search page**
Device : samsung S23 , Android 13

Logs
[Search bar issue.txt](https://github.com/chimple/cuba/files/12845201/Search.bar.issue.txt)

- [ ] **After killing the app the searched words will remain in the search bar** 

Steps to reproduce

1. Type any lesson card name in search page
2. kill the app
3. open search page again

![Screenshot_2023-10-09-15-53-08-547](https://github.com/chimple/cuba/assets/138564361/5c733ff8-3ed5-418b-98e3-de7390d58820)

- [ ] **After selecting the recent search word it will not search, we have to click on search button**

https://github.com/chimple/cuba/assets/138564361/4eb48250-851d-40e9-8890-2cb0d790b8e8

- [x] **Remove the word already entered in the search bar & searched lessons will remain after removing the text**

https://github.com/chimple/cuba/assets/138564361/6e696e3c-1874-4f22-a453-c7a7475d0d7b

- [ ] **Searched lessoncard don't have Chapter name**

![Screenshot_2023-10-09-15-53-08-547](https://github.com/chimple/cuba/assets/138564361/27fb0027-6e39-426f-b95a-c71c2183e6bb)

**Comment by Pramodmarssun** [comment]
- This issue is fixed
- Second Issue not reproduceable 
- Once we kill the app and re-open, searched text will remain in the search bar even if we switch the profile searched text will remain same 
- Here 4th issue is still happening and In Samsung s23 device recent searched suggestion is overlapping with keyboard and if we click back button keyboard and searched suggestion bar both will be disappeared
-  5th issue is not an issue
- 6th issue is still there
